name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mathijs77/test
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
